import { Cloud } from 'lucide-react';
import type { NodeDefinition } from '../types';

export const CLOUD_NODES: NodeDefinition[] = [
  {
    type: "aws",
    category: "cloud",
    label: "AWS",
    description: "Component for AWS",
    
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["aws", "cloud", "aws"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "azure",
    category: "cloud",
    label: "Azure",
    description: "Component for Azure",
    iconUrl: "/vendor-icons/azure.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["azure", "cloud", "azure"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "google_cloud",
    category: "cloud",
    label: "Google Cloud",
    description: "Component for Google Cloud",
    iconUrl: "/vendor-icons/google_cloud.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["google_cloud", "cloud", "google cloud"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "cloudflare",
    category: "cloud",
    label: "Cloudflare",
    description: "Component for Cloudflare",
    iconUrl: "/vendor-icons/cloudflare.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["cloudflare", "cloud", "cloudflare"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "vercel",
    category: "cloud",
    label: "Vercel",
    description: "Component for Vercel",
    iconUrl: "/vendor-icons/vercel.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["vercel", "cloud", "vercel"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "railway",
    category: "cloud",
    label: "Railway",
    description: "Component for Railway",
    iconUrl: "/vendor-icons/railway.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["railway", "cloud", "railway"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "render",
    category: "cloud",
    label: "Render",
    description: "Component for Render",
    iconUrl: "/vendor-icons/render.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["render", "cloud", "render"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "netlify",
    category: "cloud",
    label: "Netlify",
    description: "Component for Netlify",
    iconUrl: "/vendor-icons/netlify.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["netlify", "cloud", "netlify"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "digitalocean",
    category: "cloud",
    label: "DigitalOcean",
    description: "Component for DigitalOcean",
    iconUrl: "/vendor-icons/digitalocean.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["digitalocean", "cloud", "digitalocean"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  },
  {
    type: "fly_io",
    category: "cloud",
    label: "Fly.io",
    description: "Component for Fly.io",
    iconUrl: "/vendor-icons/fly_io.svg",
    fallbackIcon: Cloud,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["fly_io", "cloud", "fly.io"],
    tags: ["cloud"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["cloud"] }]
  }
];
