import { Server } from 'lucide-react';
import type { NodeDefinition } from '../types';

export const COMPUTE_NODES: NodeDefinition[] = [
  {
    type: "node_js",
    category: "compute",
    label: "Node.js",
    description: "Component for Node.js",
    iconUrl: "/vendor-icons/node_js.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["node_js", "compute", "node.js"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "node_js_express",
    category: "compute",
    label: "Node.js Express",
    description: "Component for Node.js Express",
    
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["node_js_express", "compute", "node.js express"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "python",
    category: "compute",
    label: "Python",
    description: "Component for Python",
    iconUrl: "/vendor-icons/python.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["python", "compute", "python"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "go",
    category: "compute",
    label: "Go",
    description: "Component for Go",
    iconUrl: "/vendor-icons/go.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["go", "compute", "go"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "go_gin",
    category: "compute",
    label: "Go (Gin)",
    description: "Component for Go (Gin)",
    
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["go_gin", "compute", "go (gin)"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "rust",
    category: "compute",
    label: "Rust",
    description: "Component for Rust",
    iconUrl: "/vendor-icons/rust.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["rust", "compute", "rust"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "rust_actix",
    category: "compute",
    label: "Rust Actix",
    description: "Component for Rust Actix",
    iconUrl: "/vendor-icons/rust_actix.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["rust_actix", "compute", "rust actix"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "java",
    category: "compute",
    label: "Java",
    description: "Component for Java",
    iconUrl: "/vendor-icons/java.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["java", "compute", "java"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "kotlin",
    category: "compute",
    label: "Kotlin",
    description: "Component for Kotlin",
    iconUrl: "/vendor-icons/kotlin.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["kotlin", "compute", "kotlin"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "php",
    category: "compute",
    label: "PHP",
    description: "Component for PHP",
    iconUrl: "/vendor-icons/php.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["php", "compute", "php"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "c",
    category: "compute",
    label: "C#",
    description: "Component for C#",
    iconUrl: "/vendor-icons/c.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["c", "compute", "c#"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "_net_core",
    category: "compute",
    label: ".NET Core",
    description: "Component for .NET Core",
    
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["_net_core", "compute", ".net core"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "ruby",
    category: "compute",
    label: "Ruby",
    description: "Component for Ruby",
    iconUrl: "/vendor-icons/ruby.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["ruby", "compute", "ruby"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "fastapi",
    category: "compute",
    label: "FastAPI",
    description: "Component for FastAPI",
    iconUrl: "/vendor-icons/fastapi.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["fastapi", "compute", "fastapi"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "django",
    category: "compute",
    label: "Django",
    description: "Component for Django",
    iconUrl: "/vendor-icons/django.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["django", "compute", "django"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "spring_boot",
    category: "compute",
    label: "Spring Boot",
    description: "Component for Spring Boot",
    iconUrl: "/vendor-icons/spring_boot.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["spring_boot", "compute", "spring boot"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "ktor",
    category: "compute",
    label: "Ktor",
    description: "Component for Ktor",
    iconUrl: "/vendor-icons/ktor.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["ktor", "compute", "ktor"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "phoenix",
    category: "compute",
    label: "Phoenix",
    description: "Component for Phoenix",
    iconUrl: "/vendor-icons/phoenix.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["phoenix", "compute", "phoenix"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "asp_net",
    category: "compute",
    label: "ASP.NET",
    description: "Component for ASP.NET",
    
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["asp_net", "compute", "asp.net"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "grpc_server",
    category: "compute",
    label: "gRPC Server",
    description: "Component for gRPC Server",
    iconUrl: "/vendor-icons/grpc_server.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["grpc_server", "compute", "grpc server"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "aws_lambda",
    category: "compute",
    label: "AWS Lambda",
    description: "Component for AWS Lambda",
    iconUrl: "/vendor-icons/aws_lambda.svg",
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["aws_lambda", "compute", "aws lambda"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }],
    propertiesSchema: [
      { name: 'runtime', label: 'Runtime', type: 'select', options: [{label: 'Node.js', value: 'nodejs'}, {label: 'Python', value: 'python'}, {label: 'Go', value: 'go'}], defaultValue: 'nodejs' },
      { name: 'timeout', label: 'Timeout (s)', type: 'number', defaultValue: 3 },
      { name: 'memory', label: 'Memory (MB)', type: 'number', defaultValue: 128 }
    ]
  },
  {
    type: "cloud_functions",
    category: "compute",
    label: "Cloud Functions",
    description: "Component for Cloud Functions",
    
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["cloud_functions", "compute", "cloud functions"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  },
  {
    type: "azure_functions",
    category: "compute",
    label: "Azure Functions",
    description: "Component for Azure Functions",
    
    fallbackIcon: Server,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["azure_functions", "compute", "azure functions"],
    tags: ["compute"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["compute"] }]
  }
];
