import { Database } from 'lucide-react';
import type { NodeDefinition } from '../types';

export const DATABASE_NODES: NodeDefinition[] = [
  {
    type: "postgresql",
    category: "database",
    label: "PostgreSQL",
    description: "Component for PostgreSQL",
    iconUrl: "/vendor-icons/postgresql.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["postgresql", "database", "postgresql"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }],
    propertiesSchema: [
      { name: 'version', label: 'Version', type: 'text', defaultValue: '14' },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 5432 },
      { name: 'storage', label: 'Storage (GB)', type: 'number', defaultValue: 20 },
      { name: 'replicas', label: 'Replicas', type: 'number', defaultValue: 1 },
    ]
  },
  {
    type: "mysql",
    category: "database",
    label: "MySQL",
    description: "Component for MySQL",
    iconUrl: "/vendor-icons/mysql.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["mysql", "database", "mysql"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "mariadb",
    category: "database",
    label: "MariaDB",
    description: "Component for MariaDB",
    iconUrl: "/vendor-icons/mariadb.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["mariadb", "database", "mariadb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "sqlite",
    category: "database",
    label: "SQLite",
    description: "Component for SQLite",
    iconUrl: "/vendor-icons/sqlite.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["sqlite", "database", "sqlite"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "mongodb",
    category: "database",
    label: "MongoDB",
    description: "Component for MongoDB",
    iconUrl: "/vendor-icons/mongodb.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["mongodb", "database", "mongodb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "redis",
    category: "database",
    label: "Redis",
    description: "Component for Redis",
    iconUrl: "/vendor-icons/redis.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["redis", "database", "redis"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "cassandra",
    category: "database",
    label: "Cassandra",
    description: "Component for Cassandra",
    iconUrl: "/vendor-icons/cassandra.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["cassandra", "database", "cassandra"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "cockroachdb",
    category: "database",
    label: "CockroachDB",
    description: "Component for CockroachDB",
    iconUrl: "/vendor-icons/cockroachdb.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["cockroachdb", "database", "cockroachdb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "dynamodb",
    category: "database",
    label: "DynamoDB",
    description: "Component for DynamoDB",
    iconUrl: "/vendor-icons/dynamodb.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["dynamodb", "database", "dynamodb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "neo4j",
    category: "database",
    label: "Neo4j",
    description: "Component for Neo4j",
    iconUrl: "/vendor-icons/neo4j.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["neo4j", "database", "neo4j"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "elasticsearch",
    category: "database",
    label: "Elasticsearch",
    description: "Component for Elasticsearch",
    iconUrl: "/vendor-icons/elasticsearch.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["elasticsearch", "database", "elasticsearch"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "opensearch",
    category: "database",
    label: "OpenSearch",
    description: "Component for OpenSearch",
    iconUrl: "/vendor-icons/opensearch.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["opensearch", "database", "opensearch"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "timescaledb",
    category: "database",
    label: "TimescaleDB",
    description: "Component for TimescaleDB",
    
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["timescaledb", "database", "timescaledb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "influxdb",
    category: "database",
    label: "InfluxDB",
    description: "Component for InfluxDB",
    iconUrl: "/vendor-icons/influxdb.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["influxdb", "database", "influxdb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "planetscale",
    category: "database",
    label: "PlanetScale",
    description: "Component for PlanetScale",
    iconUrl: "/vendor-icons/planetscale.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["planetscale", "database", "planetscale"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "supabase",
    category: "database",
    label: "Supabase",
    description: "Component for Supabase",
    iconUrl: "/vendor-icons/supabase.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["supabase", "database", "supabase"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "couchdb",
    category: "database",
    label: "CouchDB",
    description: "Component for CouchDB",
    iconUrl: "/vendor-icons/couchdb.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["couchdb", "database", "couchdb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "rethinkdb",
    category: "database",
    label: "RethinkDB",
    description: "Component for RethinkDB",
    
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["rethinkdb", "database", "rethinkdb"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  },
  {
    type: "etcd",
    category: "database",
    label: "etcd",
    description: "Component for etcd",
    iconUrl: "/vendor-icons/etcd.svg",
    fallbackIcon: Database,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["etcd", "database", "etcd"],
    tags: ["database"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["database"] }]
  }
];
