import { Workflow } from 'lucide-react';
import type { NodeDefinition } from '../types';

export const DEVOPS_NODES: NodeDefinition[] = [
  {
    type: "github_actions",
    category: "devops",
    label: "GitHub Actions",
    description: "Component for GitHub Actions",
    iconUrl: "/vendor-icons/github_actions.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["github_actions", "devops", "github actions"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "gitlab_ci",
    category: "devops",
    label: "GitLab CI",
    description: "Component for GitLab CI",
    iconUrl: "/vendor-icons/gitlab_ci.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["gitlab_ci", "devops", "gitlab ci"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "jenkins",
    category: "devops",
    label: "Jenkins",
    description: "Component for Jenkins",
    iconUrl: "/vendor-icons/jenkins.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["jenkins", "devops", "jenkins"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "terraform",
    category: "devops",
    label: "Terraform",
    description: "Component for Terraform",
    iconUrl: "/vendor-icons/terraform.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["terraform", "devops", "terraform"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "pulumi",
    category: "devops",
    label: "Pulumi",
    description: "Component for Pulumi",
    iconUrl: "/vendor-icons/pulumi.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["pulumi", "devops", "pulumi"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "circleci",
    category: "devops",
    label: "CircleCI",
    description: "Component for CircleCI",
    iconUrl: "/vendor-icons/circleci.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["circleci", "devops", "circleci"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "travis_ci",
    category: "devops",
    label: "Travis CI",
    description: "Component for Travis CI",
    iconUrl: "/vendor-icons/travis_ci.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["travis_ci", "devops", "travis ci"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "azure_devops",
    category: "devops",
    label: "Azure DevOps",
    description: "Component for Azure DevOps",
    iconUrl: "/vendor-icons/azure_devops.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["azure_devops", "devops", "azure devops"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  },
  {
    type: "ansible",
    category: "devops",
    label: "Ansible",
    description: "Component for Ansible",
    iconUrl: "/vendor-icons/ansible.svg",
    fallbackIcon: Workflow,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["ansible", "devops", "ansible"],
    tags: ["devops"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["devops"] }]
  }
];
