import { Plug } from 'lucide-react';
import type { NodeDefinition } from '../types';

export const EXTERNAL_APIS_NODES: NodeDefinition[] = [
  {
    type: "github",
    category: "external_apis",
    label: "GitHub",
    description: "Component for GitHub",
    iconUrl: "/vendor-icons/github.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["github", "external_apis", "github"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "gitlab",
    category: "external_apis",
    label: "GitLab",
    description: "Component for GitLab",
    iconUrl: "/vendor-icons/gitlab.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["gitlab", "external_apis", "gitlab"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "slack",
    category: "external_apis",
    label: "Slack",
    description: "Component for Slack",
    iconUrl: "/vendor-icons/slack.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["slack", "external_apis", "slack"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "discord",
    category: "external_apis",
    label: "Discord",
    description: "Component for Discord",
    iconUrl: "/vendor-icons/discord.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["discord", "external_apis", "discord"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "gmail",
    category: "external_apis",
    label: "Gmail",
    description: "Component for Gmail",
    iconUrl: "/vendor-icons/gmail.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["gmail", "external_apis", "gmail"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "outlook",
    category: "external_apis",
    label: "Outlook",
    description: "Component for Outlook",
    
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["outlook", "external_apis", "outlook"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "stripe",
    category: "external_apis",
    label: "Stripe",
    description: "Component for Stripe",
    iconUrl: "/vendor-icons/stripe.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["stripe", "external_apis", "stripe"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "razorpay",
    category: "external_apis",
    label: "Razorpay",
    description: "Component for Razorpay",
    iconUrl: "/vendor-icons/razorpay.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["razorpay", "external_apis", "razorpay"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "twilio",
    category: "external_apis",
    label: "Twilio",
    description: "Component for Twilio",
    iconUrl: "/vendor-icons/twilio.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["twilio", "external_apis", "twilio"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "notion",
    category: "external_apis",
    label: "Notion",
    description: "Component for Notion",
    iconUrl: "/vendor-icons/notion.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["notion", "external_apis", "notion"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "jira",
    category: "external_apis",
    label: "Jira",
    description: "Component for Jira",
    iconUrl: "/vendor-icons/jira.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["jira", "external_apis", "jira"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "shopify",
    category: "external_apis",
    label: "Shopify",
    description: "Component for Shopify",
    iconUrl: "/vendor-icons/shopify.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["shopify", "external_apis", "shopify"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "sendgrid",
    category: "external_apis",
    label: "SendGrid",
    description: "Component for SendGrid",
    iconUrl: "/vendor-icons/sendgrid.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["sendgrid", "external_apis", "sendgrid"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "firebase",
    category: "external_apis",
    label: "Firebase",
    description: "Component for Firebase",
    iconUrl: "/vendor-icons/firebase.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["firebase", "external_apis", "firebase"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  },
  {
    type: "supabase",
    category: "external_apis",
    label: "Supabase",
    description: "Component for Supabase",
    iconUrl: "/vendor-icons/supabase.svg",
    fallbackIcon: Plug,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["supabase", "external_apis", "supabase"],
    tags: ["external_apis"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["external_apis"] }]
  }
];
