import { Monitor } from 'lucide-react';
import type { NodeDefinition } from '../types';

export const FRONTEND_NODES: NodeDefinition[] = [
  {
    type: "react",
    category: "frontend",
    label: "React",
    description: "Component for React",
    iconUrl: "/vendor-icons/react.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["react", "frontend", "react"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "next_js",
    category: "frontend",
    label: "Next.js",
    description: "Component for Next.js",
    iconUrl: "/vendor-icons/next_js.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["next_js", "frontend", "next.js"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "vue",
    category: "frontend",
    label: "Vue",
    description: "Component for Vue",
    iconUrl: "/vendor-icons/vue.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["vue", "frontend", "vue"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "nuxt",
    category: "frontend",
    label: "Nuxt",
    description: "Component for Nuxt",
    iconUrl: "/vendor-icons/nuxt.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["nuxt", "frontend", "nuxt"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "svelte",
    category: "frontend",
    label: "Svelte",
    description: "Component for Svelte",
    iconUrl: "/vendor-icons/svelte.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["svelte", "frontend", "svelte"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "angular",
    category: "frontend",
    label: "Angular",
    description: "Component for Angular",
    iconUrl: "/vendor-icons/angular.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["angular", "frontend", "angular"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "astro",
    category: "frontend",
    label: "Astro",
    description: "Component for Astro",
    iconUrl: "/vendor-icons/astro.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["astro", "frontend", "astro"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "qwik",
    category: "frontend",
    label: "Qwik",
    description: "Component for Qwik",
    iconUrl: "/vendor-icons/qwik.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["qwik", "frontend", "qwik"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "gatsby",
    category: "frontend",
    label: "Gatsby",
    description: "Component for Gatsby",
    iconUrl: "/vendor-icons/gatsby.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["gatsby", "frontend", "gatsby"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "htmx",
    category: "frontend",
    label: "HTMX",
    description: "Component for HTMX",
    iconUrl: "/vendor-icons/htmx.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["htmx", "frontend", "htmx"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "lit",
    category: "frontend",
    label: "Lit",
    description: "Component for Lit",
    iconUrl: "/vendor-icons/lit.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["lit", "frontend", "lit"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "alpine_js",
    category: "frontend",
    label: "Alpine.js",
    description: "Component for Alpine.js",
    iconUrl: "/vendor-icons/alpine_js.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["alpine_js", "frontend", "alpine.js"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "tailwindcss",
    category: "frontend",
    label: "TailwindCSS",
    description: "Component for TailwindCSS",
    iconUrl: "/vendor-icons/tailwindcss.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["tailwindcss", "frontend", "tailwindcss"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "redux",
    category: "frontend",
    label: "Redux",
    description: "Component for Redux",
    iconUrl: "/vendor-icons/redux.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["redux", "frontend", "redux"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "zustand",
    category: "frontend",
    label: "Zustand",
    description: "Component for Zustand",
    iconUrl: "/vendor-icons/zustand.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["zustand", "frontend", "zustand"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  },
  {
    type: "remix",
    category: "frontend",
    label: "Remix",
    description: "Component for Remix",
    iconUrl: "/vendor-icons/remix.svg",
    fallbackIcon: Monitor,
    accentColor: "oklch(0.6 0.15 250)",
    shape: "rectangle",
    keywords: ["remix", "frontend", "remix"],
    tags: ["frontend"],
    defaultVariant: "standard",
    variants: [{ id: "standard", label: "Standard", description: "Default variant", tags: ["frontend"] }]
  }
];
