import { toPng, toSvg } from 'html-to-image';
import { getLayoutedElements } from './flowLayout';
import type { ArchNode, ArchEdge } from './types';

export async function exportToImage(fileName: string = 'architecture') {
  // Find the react-flow container
  const flowContainer = document.querySelector('.react-flow__pane') as HTMLElement || document.querySelector('.react-flow') as HTMLElement;
  
  if (!flowContainer) {
    throw new Error('Canvas not found');
  }

  // Temporarily add a background color for the export if it's transparent
  const originalBg = flowContainer.style.backgroundColor;
  flowContainer.style.backgroundColor = '#FFFFFF';

  try {
    const dataUrl = await toPng(flowContainer, { 
      quality: 1.0, 
      pixelRatio: 2,
      backgroundColor: '#FFFFFF',
      filter: (node) => {
        // Exclude UI controls from export
        if (node?.classList?.contains('react-flow__controls')) return false;
        if (node?.classList?.contains('react-flow__minimap')) return false;
        if (node?.classList?.contains('react-flow__panel')) return false;
        return true;
      }
    });

    // Create a download link
    const link = document.createElement('a');
    link.download = `${fileName}-${Date.now()}.png`;
    link.href = dataUrl;
    link.click();
  } catch (error) {
    console.error('Failed to export image:', error);
    throw error;
  } finally {
    flowContainer.style.backgroundColor = originalBg;
  }
}

export function exportToJson(graph: { nodes: ArchNode[], edges: ArchEdge[], project_name?: string }, fileName: string = 'architecture') {
  const data = JSON.stringify(graph, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.download = `${fileName}-${Date.now()}.json`;
  link.href = url;
  link.click();
  
  URL.revokeObjectURL(url);
}

export function exportToTerraform(graph: { nodes: ArchNode[], edges: ArchEdge[] }, fileName: string = 'main') {
  // Simple Terraform mock generator for Phase 4
  let tf = `# Auto-generated by IsoStack\n\n`;
  
  graph.nodes.forEach(node => {
    const safeName = node.label.toLowerCase().replace(/[^a-z0-9]/g, '_');
    if (node.serviceType === 'aws_lambda' || node.serviceType === 'lambda') {
      tf += `resource "aws_lambda_function" "${safeName}" {\n`;
      tf += `  function_name = "${safeName}"\n`;
      tf += `  runtime       = "nodejs18.x"\n`;
      tf += `  handler       = "index.handler"\n`;
      tf += `}\n\n`;
    } else if (node.serviceType === 's3' || node.serviceType === 'aws_s3') {
      tf += `resource "aws_s3_bucket" "${safeName}" {\n`;
      tf += `  bucket = "${safeName}-bucket"\n`;
      tf += `}\n\n`;
    } else if (node.serviceType === 'postgresql' || node.serviceType === 'mysql') {
      tf += `resource "aws_db_instance" "${safeName}" {\n`;
      tf += `  engine               = "${node.serviceType}"\n`;
      tf += `  instance_class       = "db.t3.micro"\n`;
      tf += `  allocated_storage    = 20\n`;
      tf += `}\n\n`;
    } else {
      tf += `# Placeholder for ${node.label} (${node.serviceType})\n`;
      tf += `resource "mock_resource" "${safeName}" {\n`;
      tf += `  name = "${node.label}"\n`;
      tf += `}\n\n`;
    }
  });

  const blob = new Blob([tf], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.download = `${fileName}-${Date.now()}.tf`;
  link.href = url;
  link.click();
  
  URL.revokeObjectURL(url);
}
