import { 
  Zap, Code, Database, Server, Cpu, Monitor, MessageSquare, 
  Box, Globe, Shield, BarChart3, Lock, CreditCard, Mail, Phone, 
  Bell, Sparkles, Search, Container, Workflow, Cloud, Radio
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface ServiceVariant {
  id: string;
  label: string;
  description: string;
  tags: string[];
}

export interface Service {
  type: string;
  category: string;
  label: string;
  description: string;
  defaultVariant: string;
  variants: ServiceVariant[];
  icon: LucideIcon;
  accentColor: string;
}

export const CATEGORY_CONFIG: Record<string, { label: string; color: string; bgColor: string; borderColor: string; icon: LucideIcon; order: number; }> = {
  backend:        { label: "Compute / Backend",    color: "oklch(0.55 0.2 260)",  bgColor: "bg-blue-500/20",    borderColor: "border-blue-500/30",    icon: Cpu,          order: 0 },
  frontend:       { label: "Frontend",             color: "oklch(0.6 0.18 200)",  bgColor: "bg-cyan-500/20",    borderColor: "border-cyan-500/30",    icon: Monitor,      order: 1 },
  database:       { label: "Data / Storage",       color: "oklch(0.6 0.12 250)",  bgColor: "bg-blue-400/20",    borderColor: "border-blue-400/30",    icon: Database,     order: 2 },
  cache:          { label: "Cache",                color: "oklch(0.55 0.2 30)",   bgColor: "bg-orange-500/20",  borderColor: "border-orange-500/30",  icon: Zap,          order: 3 },
  messaging:      { label: "Messaging",            color: "oklch(0.65 0.18 45)",  bgColor: "bg-amber-500/20",   borderColor: "border-amber-500/30",   icon: MessageSquare,order: 4 },
  infrastructure: { label: "Infrastructure",       color: "oklch(0.6 0.15 280)",  bgColor: "bg-purple-500/20",  borderColor: "border-purple-500/30",  icon: Server,       order: 5 },
  ai:             { label: "AI / LLM",             color: "oklch(0.6 0.18 160)",  bgColor: "bg-teal-500/20",    borderColor: "border-teal-500/30",    icon: Sparkles,     order: 6 },
  monitoring:     { label: "Monitoring",           color: "oklch(0.65 0.18 50)",  bgColor: "bg-amber-600/20",   borderColor: "border-amber-600/30",   icon: BarChart3,    order: 7 },
  custom:         { label: "Custom Nodes",         color: "oklch(0.7 0.1 100)",   bgColor: "bg-emerald-500/20", borderColor: "border-emerald-500/30", icon: Box,          order: 8 },
};

export const SERVICE_CATALOG: Service[] = [
  // Backend
  { type: "fastapi", category: "backend", label: "FastAPI", description: "Modern async Python API", defaultVariant: "rest", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "rest", label: "REST API", description: "Standard REST API", tags: ["backend", "python", "async"] }] },
  { type: "django", category: "backend", label: "Django", description: "Full-featured Python web framework", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "python", "monolith"] }] },
  { type: "nodejs", category: "backend", label: "Node.js Express", description: "Standard JS backend", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "javascript"] }] },
  { type: "go", category: "backend", label: "Go (Gin)", description: "High-performance Go", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "go"] }] },
  { type: "rust_actix", category: "backend", label: "Rust Actix", description: "Ultra-fast Rust", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "rust"] }] },
  { type: "spring_boot", category: "backend", label: "Spring Boot", description: "Enterprise Java", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "java"] }] },
  { type: "dotnet", category: "backend", label: ".NET Core", description: "Microsoft enterprise backend", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "csharp"] }] },
  { type: "ktor", category: "backend", label: "Ktor", description: "Kotlin async framework", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "kotlin"] }] },
  { type: "phoenix", category: "backend", label: "Phoenix", description: "Elixir real-time framework", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "elixir"] }] },
  { type: "grpc_server", category: "backend", label: "gRPC Server", description: "High-perf RPC", defaultVariant: "standard", icon: Cpu, accentColor: "oklch(0.55 0.2 260)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["backend", "grpc"] }] },
  // Frontend
  { type: "react", category: "frontend", label: "React", description: "UI library for interfaces", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "react"] }] },
  { type: "nextjs", category: "frontend", label: "Next.js", description: "React with SSR", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "react", "ssr"] }] },
  { type: "vue", category: "frontend", label: "Vue.js", description: "Progressive JS framework", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "vue"] }] },
  { type: "nuxt", category: "frontend", label: "Nuxt 3", description: "Vue SSR framework", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "vue", "ssr"] }] },
  { type: "svelte", category: "frontend", label: "Svelte", description: "Compiler-based framework", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "svelte"] }] },
  { type: "angular", category: "frontend", label: "Angular", description: "Enterprise SPA framework", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "angular"] }] },
  { type: "flutter", category: "frontend", label: "Flutter", description: "Cross-platform mobile/web", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "dart", "mobile"] }] },
  { type: "remix", category: "frontend", label: "Remix", description: "Full-stack React", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "react", "ssr"] }] },
  { type: "astro", category: "frontend", label: "Astro", description: "Static islands architecture", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "static"] }] },
  { type: "qwik", category: "frontend", label: "Qwik", description: "Resumable frontend", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "resumable"] }] },
  { type: "gatsby", category: "frontend", label: "Gatsby", description: "React static site generator", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "react", "static"] }] },
  { type: "htmx", category: "frontend", label: "HTMX", description: "HTML-over-the-wire", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "html"] }] },
  { type: "lit", category: "frontend", label: "Lit", description: "Web components", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "components"] }] },
  { type: "alpine_js", category: "frontend", label: "Alpine.js", description: "Minimal JS framework", defaultVariant: "standard", icon: Monitor, accentColor: "oklch(0.6 0.18 200)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["frontend", "js"] }] },
  // Database
  { type: "postgresql", category: "database", label: "PostgreSQL", description: "Advanced relational DB", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql"] }] },
  { type: "mysql", category: "database", label: "MySQL", description: "Popular relational DB", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql"] }] },
  { type: "mariadb", category: "database", label: "MariaDB", description: "Open-source MySQL fork", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql"] }] },
  { type: "mongodb", category: "database", label: "MongoDB", description: "NoSQL document DB", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "nosql"] }] },
  { type: "dynamodb", category: "database", label: "DynamoDB", description: "AWS serverless NoSQL", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "nosql", "aws"] }] },
  { type: "firebase", category: "database", label: "Firebase DB", description: "Realtime NoSQL", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "nosql", "google"] }] },
  { type: "cassandra", category: "database", label: "Cassandra", description: "Distributed wide-column", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "nosql"] }] },
  { type: "elasticsearch", category: "database", label: "Elasticsearch", description: "Search engine", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "search"] }] },
  { type: "neo4j", category: "database", label: "Neo4j", description: "Graph database", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "graph"] }] },
  { type: "influxdb", category: "database", label: "InfluxDB", description: "Time-series DB", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "timeseries"] }] },
  { type: "cockroachdb", category: "database", label: "CockroachDB", description: "Distributed SQL", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql"] }] },
  { type: "planetscale", category: "database", label: "PlanetScale", description: "Serverless MySQL", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql", "serverless"] }] },
  { type: "supabase", category: "database", label: "Supabase", description: "Managed Postgres & Auth", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql"] }] },
  { type: "couchdb", category: "database", label: "CouchDB", description: "Document DB with sync", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "nosql"] }] },
  { type: "rethinkdb", category: "database", label: "RethinkDB", description: "Realtime JSON DB", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "nosql"] }] },
  { type: "sqlite", category: "database", label: "SQLite", description: "Embedded SQL DB", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "sql"] }] },
  { type: "etcd", category: "database", label: "etcd", description: "Distributed key-value store", defaultVariant: "standard", icon: Database, accentColor: "oklch(0.6 0.12 250)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["database", "kv"] }] },
  // Cache
  { type: "redis", category: "cache", label: "Redis", description: "In-memory data store", defaultVariant: "standard", icon: Zap, accentColor: "oklch(0.55 0.2 30)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["cache"] }] },
  { type: "memcached", category: "cache", label: "Memcached", description: "Distributed memory cache", defaultVariant: "standard", icon: Zap, accentColor: "oklch(0.55 0.2 30)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["cache"] }] },
  // Messaging
  { type: "rabbitmq", category: "messaging", label: "RabbitMQ", description: "AMQP broker", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "queue"] }] },
  { type: "kafka", category: "messaging", label: "Kafka", description: "Event streaming platform", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "streaming"] }] },
  { type: "sqs", category: "messaging", label: "AWS SQS", description: "Managed message queue", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "aws"] }] },
  { type: "pubsub_gcp", category: "messaging", label: "GCP Pub/Sub", description: "Global messaging", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "gcp"] }] },
  { type: "nats", category: "messaging", label: "NATS", description: "Cloud-native messaging", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging"] }] },
  { type: "nats_streaming", category: "messaging", label: "JetStream", description: "Persistent NATS", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging"] }] },
  { type: "pulsar", category: "messaging", label: "Apache Pulsar", description: "Distributed messaging", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging"] }] },
  { type: "mqtt", category: "messaging", label: "MQTT Broker", description: "IoT messaging", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "iot"] }] },
  { type: "zeromq", category: "messaging", label: "ZeroMQ", description: "High-perf async messaging", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging"] }] },
  { type: "celery", category: "messaging", label: "Celery", description: "Python task queue", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "python"] }] },
  { type: "rq", category: "messaging", label: "RQ", description: "Simple Redis queue", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "python"] }] },
  { type: "temporal", category: "messaging", label: "Temporal", description: "Workflow orchestration", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "workflow"] }] },
  { type: "airflow", category: "messaging", label: "Airflow", description: "Data pipeline orchestration", defaultVariant: "standard", icon: MessageSquare, accentColor: "oklch(0.65 0.18 45)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["messaging", "workflow"] }] },
  // Infrastructure
  { type: "aws_lambda", category: "infrastructure", label: "AWS Lambda", description: "Serverless compute", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "aws", "serverless"] }] },
  { type: "gcp_functions", category: "infrastructure", label: "GCP Functions", description: "Google serverless", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "gcp", "serverless"] }] },
  { type: "azure_functions", category: "infrastructure", label: "Azure Functions", description: "Microsoft serverless", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "azure", "serverless"] }] },
  { type: "api_gateway", category: "infrastructure", label: "AWS API Gateway", description: "Managed gateway", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "aws"] }] },
  { type: "kong", category: "infrastructure", label: "Kong", description: "API Gateway", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "gateway"] }] },
  { type: "traefik", category: "infrastructure", label: "Traefik", description: "Cloud-native proxy", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "proxy"] }] },
  { type: "kubernetes", category: "infrastructure", label: "Kubernetes", description: "Container orchestration", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "containers"] }] },
  { type: "docker", category: "infrastructure", label: "Docker Swarm", description: "Container cluster", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "containers"] }] },
  { type: "algolia", category: "infrastructure", label: "Algolia", description: "Hosted search", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "search"] }] },
  { type: "meilisearch", category: "infrastructure", label: "Meilisearch", description: "Fast open-source search", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "search"] }] },
  { type: "cloudflare", category: "infrastructure", label: "Cloudflare", description: "CDN and Edge", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "cdn"] }] },
  { type: "aws_cloudfront", category: "infrastructure", label: "CloudFront", description: "AWS CDN", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "cdn", "aws"] }] },
  { type: "s3", category: "infrastructure", label: "AWS S3", description: "Object storage", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "storage", "aws"] }] },
  { type: "gcs", category: "infrastructure", label: "Google Cloud Storage", description: "GCP object storage", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "storage", "gcp"] }] },
  { type: "minio", category: "infrastructure", label: "MinIO", description: "S3-compatible storage", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "storage"] }] },
  { type: "supabase_storage", category: "infrastructure", label: "Supabase Storage", description: "Postgres-backed storage", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "storage"] }] },
  { type: "backblaze", category: "infrastructure", label: "Backblaze B2", description: "Affordable cloud storage", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "storage"] }] },
  { type: "linode_storage", category: "infrastructure", label: "Linode Object Storage", description: "Akamai storage", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "storage"] }] },
  { type: "auth0", category: "infrastructure", label: "Auth0", description: "Managed identity", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "auth"] }] },
  { type: "keycloak", category: "infrastructure", label: "Keycloak", description: "Self-hosted IAM", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "auth"] }] },
  { type: "oauth2_server", category: "infrastructure", label: "OAuth2 Server", description: "Custom auth server", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "auth"] }] },
  { type: "stripe", category: "infrastructure", label: "Stripe", description: "Payments", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "payments"] }] },
  { type: "razorpay", category: "infrastructure", label: "Razorpay", description: "Payments (India)", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "payments"] }] },
  { type: "sendgrid", category: "infrastructure", label: "SendGrid", description: "Transactional email", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "email"] }] },
  { type: "twilio", category: "infrastructure", label: "Twilio", description: "SMS and Voice", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "sms"] }] },
  { type: "fcm", category: "infrastructure", label: "Firebase Cloud Messaging", description: "Push notifications", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "push"] }] },
  { type: "vault", category: "infrastructure", label: "HashiCorp Vault", description: "Secrets management", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "secrets"] }] },
  { type: "consul", category: "infrastructure", label: "Consul", description: "Service mesh & discovery", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "mesh"] }] },
  { type: "istio", category: "infrastructure", label: "Istio", description: "Service mesh", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "mesh"] }] },
  { type: "linkerd", category: "infrastructure", label: "Linkerd", description: "Lightweight service mesh", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "mesh"] }] },
  { type: "envoy", category: "infrastructure", label: "Envoy", description: "Edge and service proxy", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "proxy"] }] },
  { type: "nginx", category: "infrastructure", label: "Nginx", description: "Web server & proxy", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "proxy", "web"] }] },
  { type: "apache", category: "infrastructure", label: "Apache HTTP", description: "Web server", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "web"] }] },
  { type: "caddy", category: "infrastructure", label: "Caddy", description: "Web server with auto-HTTPS", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "web", "https"] }] },
  { type: "haproxy", category: "infrastructure", label: "HAProxy", description: "Load balancer", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "proxy"] }] },
  { type: "github_actions", category: "infrastructure", label: "GitHub Actions", description: "CI/CD pipeline", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "ci-cd"] }] },
  { type: "gitlab_ci", category: "infrastructure", label: "GitLab CI", description: "Integrated CI/CD", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "ci-cd"] }] },
  { type: "jenkins", category: "infrastructure", label: "Jenkins", description: "Automation server", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "ci-cd"] }] },
  { type: "circleci", category: "infrastructure", label: "CircleCI", description: "Continuous integration", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "ci-cd"] }] },
  { type: "travis_ci", category: "infrastructure", label: "Travis CI", description: "Hosted CI", defaultVariant: "standard", icon: Server, accentColor: "oklch(0.6 0.15 280)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["infrastructure", "ci-cd"] }] },
  // Monitoring
  { type: "prometheus", category: "monitoring", label: "Prometheus", description: "Metrics & alerting", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "metrics"] }] },
  { type: "grafana", category: "monitoring", label: "Grafana", description: "Dashboards", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "dashboards"] }] },
  { type: "elk", category: "monitoring", label: "ELK Stack", description: "Elastic, Logstash, Kibana", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "logging"] }] },
  { type: "datadog", category: "monitoring", label: "Datadog", description: "Cloud observability", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "apm"] }] },
  { type: "jaeger", category: "monitoring", label: "Jaeger", description: "Distributed tracing", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "tracing"] }] },
  { type: "tempo", category: "monitoring", label: "Grafana Tempo", description: "High-scale tracing", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "tracing"] }] },
  { type: "loki", category: "monitoring", label: "Grafana Loki", description: "Log aggregation", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "logging"] }] },
  { type: "honeycomb", category: "monitoring", label: "Honeycomb", description: "Observability platform", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "observability"] }] },
  { type: "newrelic", category: "monitoring", label: "New Relic", description: "APM & monitoring", defaultVariant: "standard", icon: BarChart3, accentColor: "oklch(0.65 0.18 50)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["monitoring", "apm"] }] },
  // AI
  { type: "openai_api", category: "ai", label: "OpenAI API", description: "GPT models", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "llm"] }] },
  { type: "huggingface", category: "ai", label: "Hugging Face", description: "ML model hub", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "ml"] }] },
  { type: "vertex_ai", category: "ai", label: "Vertex AI", description: "Google ML platform", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "google"] }] },
  { type: "claude_api", category: "ai", label: "Claude API", description: "Anthropic AI", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "llm"] }] },
  { type: "google_ai", category: "ai", label: "Google AI Studio", description: "Gemini models", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "gemini"] }] },
  { type: "cohere_api", category: "ai", label: "Cohere API", description: "Enterprise LLMs", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "llm"] }] },
  { type: "replicate", category: "ai", label: "Replicate", description: "Run open-source models", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "models"] }] },
  { type: "together_ai", category: "ai", label: "Together AI", description: "Fast open-source inference", defaultVariant: "standard", icon: Sparkles, accentColor: "oklch(0.6 0.18 160)", variants: [{ id: "standard", label: "Standard", description: "Standard deployment", tags: ["ai", "inference"] }] }
];

export const CONNECTION_RULES: Record<string, string[]> = {};
export const canConnect = (source: string, target: string): boolean => true;
